apiVersion: apps/v1
kind: Deployment
metadata:
  name: site1
spec:
  replicas: 6
  selector: 
    matchLabels:
      app: site1
  template:
    metadata:
      labels:
        app: site1
    spec:
      containers:
      - name: site1
        image: guigapc/site1:latest
---
apiVersion: v1
kind: Service
metadata:
  name: site1
spec:
  selector:
    app: site1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort